name: Skip Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  skip_job:
    if: contains(github.event.pull_request.labels.*.name, 'merge-queue-only') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your checks
        run: |
          echo "Running checks..."
          # Add your check commands here
